/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R5YearWarrantyRouteImport } from './routes/5-year-warranty'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BookingFormRouteImport } from './routes/booking-form'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ClearsmileAlignersRouteImport } from './routes/clearsmile-aligners'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CrownsRouteImport } from './routes/crowns'
import { Route as DentalLabUaeRouteImport } from './routes/dental-lab-uae'
import { Route as DenturesRouteImport } from './routes/dentures'
import { Route as DigitalImpressionsRouteImport } from './routes/digital-impressions'
import { Route as DigitalProductsRouteImport } from './routes/digital-products'
import { Route as ImplantRestorationsRouteImport } from './routes/implant-restorations'
import { Route as InlayOnlayRouteImport } from './routes/inlay-onlay'
import { Route as InmanAlignerRouteImport } from './routes/inman-aligner'
import { Route as MdentTeamRouteImport } from './routes/mdent-team'
import { Route as MessageFromTheFounderRouteImport } from './routes/message-from-the-founder'
import { Route as NightGuardsRouteImport } from './routes/night-guards'
import { Route as OrthodonticsRouteImport } from './routes/orthodontics'
import { Route as OurClientsRouteImport } from './routes/our-clients'
import { Route as PastEventsRouteImport } from './routes/past-events'
import { Route as RegularImpressionsRouteImport } from './routes/regular-impressions'
import { Route as ShadeMatchingRouteImport } from './routes/shade-matching'
import { Route as SleepApneaApplianceRouteImport } from './routes/sleep-apnea-appliance'
import { Route as SmileDesignRouteImport } from './routes/smile-design'
import { Route as SportsGuardsRouteImport } from './routes/sports-guards'
import { Route as SurgicalGuideRouteImport } from './routes/surgical-guide'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as UpcomingEventsRouteImport } from './routes/upcoming-events'
import { Route as VeneersRouteImport } from './routes/veneers'
import { Route as WorldWideDeliveryRouteImport } from './routes/world-wide-delivery'
import { Route as MdentNewsIndexRouteImport } from './routes/mdent-news.index'
import { Route as MdentNewsSlugRouteImport } from './routes/mdent-news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R5YearWarrantyRoute = R5YearWarrantyRouteImport.update({
  id: '/5-year-warranty',
  path: '/5-year-warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFormRoute = BookingFormRouteImport.update({
  id: '/booking-form',
  path: '/booking-form',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearsmileAlignersRoute = ClearsmileAlignersRouteImport.update({
  id: '/clearsmile-aligners',
  path: '/clearsmile-aligners',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CrownsRoute = CrownsRouteImport.update({
  id: '/crowns',
  path: '/crowns',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalLabUaeRoute = DentalLabUaeRouteImport.update({
  id: '/dental-lab-uae',
  path: '/dental-lab-uae',
  getParentRoute: () => rootRouteImport,
} as any)
const DenturesRoute = DenturesRouteImport.update({
  id: '/dentures',
  path: '/dentures',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalImpressionsRoute = DigitalImpressionsRouteImport.update({
  id: '/digital-impressions',
  path: '/digital-impressions',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalProductsRoute = DigitalProductsRouteImport.update({
  id: '/digital-products',
  path: '/digital-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantRestorationsRoute = ImplantRestorationsRouteImport.update({
  id: '/implant-restorations',
  path: '/implant-restorations',
  getParentRoute: () => rootRouteImport,
} as any)
const InlayOnlayRoute = InlayOnlayRouteImport.update({
  id: '/inlay-onlay',
  path: '/inlay-onlay',
  getParentRoute: () => rootRouteImport,
} as any)
const InmanAlignerRoute = InmanAlignerRouteImport.update({
  id: '/inman-aligner',
  path: '/inman-aligner',
  getParentRoute: () => rootRouteImport,
} as any)
const MdentTeamRoute = MdentTeamRouteImport.update({
  id: '/mdent-team',
  path: '/mdent-team',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageFromTheFounderRoute = MessageFromTheFounderRouteImport.update({
  id: '/message-from-the-founder',
  path: '/message-from-the-founder',
  getParentRoute: () => rootRouteImport,
} as any)
const NightGuardsRoute = NightGuardsRouteImport.update({
  id: '/night-guards',
  path: '/night-guards',
  getParentRoute: () => rootRouteImport,
} as any)
const OrthodonticsRoute = OrthodonticsRouteImport.update({
  id: '/orthodontics',
  path: '/orthodontics',
  getParentRoute: () => rootRouteImport,
} as any)
const OurClientsRoute = OurClientsRouteImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const PastEventsRoute = PastEventsRouteImport.update({
  id: '/past-events',
  path: '/past-events',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularImpressionsRoute = RegularImpressionsRouteImport.update({
  id: '/regular-impressions',
  path: '/regular-impressions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadeMatchingRoute = ShadeMatchingRouteImport.update({
  id: '/shade-matching',
  path: '/shade-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepApneaApplianceRoute = SleepApneaApplianceRouteImport.update({
  id: '/sleep-apnea-appliance',
  path: '/sleep-apnea-appliance',
  getParentRoute: () => rootRouteImport,
} as any)
const SmileDesignRoute = SmileDesignRouteImport.update({
  id: '/smile-design',
  path: '/smile-design',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsGuardsRoute = SportsGuardsRouteImport.update({
  id: '/sports-guards',
  path: '/sports-guards',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgicalGuideRoute = SurgicalGuideRouteImport.update({
  id: '/surgical-guide',
  path: '/surgical-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingEventsRoute = UpcomingEventsRouteImport.update({
  id: '/upcoming-events',
  path: '/upcoming-events',
  getParentRoute: () => rootRouteImport,
} as any)
const VeneersRoute = VeneersRouteImport.update({
  id: '/veneers',
  path: '/veneers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldWideDeliveryRoute = WorldWideDeliveryRouteImport.update({
  id: '/world-wide-delivery',
  path: '/world-wide-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const MdentNewsIndexRoute = MdentNewsIndexRouteImport.update({
  id: '/mdent-news/',
  path: '/mdent-news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MdentNewsSlugRoute = MdentNewsSlugRouteImport.update({
  id: '/mdent-news/$slug',
  path: '/mdent-news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/5-year-warranty': typeof R5YearWarrantyRoute
  '/about-us': typeof AboutUsRoute
  '/booking-form': typeof BookingFormRoute
  '/careers': typeof CareersRoute
  '/clearsmile-aligners': typeof ClearsmileAlignersRoute
  '/contact-us': typeof ContactUsRoute
  '/crowns': typeof CrownsRoute
  '/dental-lab-uae': typeof DentalLabUaeRoute
  '/dentures': typeof DenturesRoute
  '/digital-impressions': typeof DigitalImpressionsRoute
  '/digital-products': typeof DigitalProductsRoute
  '/implant-restorations': typeof ImplantRestorationsRoute
  '/inlay-onlay': typeof InlayOnlayRoute
  '/inman-aligner': typeof InmanAlignerRoute
  '/mdent-team': typeof MdentTeamRoute
  '/message-from-the-founder': typeof MessageFromTheFounderRoute
  '/night-guards': typeof NightGuardsRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/our-clients': typeof OurClientsRoute
  '/past-events': typeof PastEventsRoute
  '/regular-impressions': typeof RegularImpressionsRoute
  '/shade-matching': typeof ShadeMatchingRoute
  '/sleep-apnea-appliance': typeof SleepApneaApplianceRoute
  '/smile-design': typeof SmileDesignRoute
  '/sports-guards': typeof SportsGuardsRoute
  '/surgical-guide': typeof SurgicalGuideRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/veneers': typeof VeneersRoute
  '/world-wide-delivery': typeof WorldWideDeliveryRoute
  '/mdent-news/$slug': typeof MdentNewsSlugRoute
  '/mdent-news/': typeof MdentNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/5-year-warranty': typeof R5YearWarrantyRoute
  '/about-us': typeof AboutUsRoute
  '/booking-form': typeof BookingFormRoute
  '/careers': typeof CareersRoute
  '/clearsmile-aligners': typeof ClearsmileAlignersRoute
  '/contact-us': typeof ContactUsRoute
  '/crowns': typeof CrownsRoute
  '/dental-lab-uae': typeof DentalLabUaeRoute
  '/dentures': typeof DenturesRoute
  '/digital-impressions': typeof DigitalImpressionsRoute
  '/digital-products': typeof DigitalProductsRoute
  '/implant-restorations': typeof ImplantRestorationsRoute
  '/inlay-onlay': typeof InlayOnlayRoute
  '/inman-aligner': typeof InmanAlignerRoute
  '/mdent-team': typeof MdentTeamRoute
  '/message-from-the-founder': typeof MessageFromTheFounderRoute
  '/night-guards': typeof NightGuardsRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/our-clients': typeof OurClientsRoute
  '/past-events': typeof PastEventsRoute
  '/regular-impressions': typeof RegularImpressionsRoute
  '/shade-matching': typeof ShadeMatchingRoute
  '/sleep-apnea-appliance': typeof SleepApneaApplianceRoute
  '/smile-design': typeof SmileDesignRoute
  '/sports-guards': typeof SportsGuardsRoute
  '/surgical-guide': typeof SurgicalGuideRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/veneers': typeof VeneersRoute
  '/world-wide-delivery': typeof WorldWideDeliveryRoute
  '/mdent-news/$slug': typeof MdentNewsSlugRoute
  '/mdent-news': typeof MdentNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/5-year-warranty': typeof R5YearWarrantyRoute
  '/about-us': typeof AboutUsRoute
  '/booking-form': typeof BookingFormRoute
  '/careers': typeof CareersRoute
  '/clearsmile-aligners': typeof ClearsmileAlignersRoute
  '/contact-us': typeof ContactUsRoute
  '/crowns': typeof CrownsRoute
  '/dental-lab-uae': typeof DentalLabUaeRoute
  '/dentures': typeof DenturesRoute
  '/digital-impressions': typeof DigitalImpressionsRoute
  '/digital-products': typeof DigitalProductsRoute
  '/implant-restorations': typeof ImplantRestorationsRoute
  '/inlay-onlay': typeof InlayOnlayRoute
  '/inman-aligner': typeof InmanAlignerRoute
  '/mdent-team': typeof MdentTeamRoute
  '/message-from-the-founder': typeof MessageFromTheFounderRoute
  '/night-guards': typeof NightGuardsRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/our-clients': typeof OurClientsRoute
  '/past-events': typeof PastEventsRoute
  '/regular-impressions': typeof RegularImpressionsRoute
  '/shade-matching': typeof ShadeMatchingRoute
  '/sleep-apnea-appliance': typeof SleepApneaApplianceRoute
  '/smile-design': typeof SmileDesignRoute
  '/sports-guards': typeof SportsGuardsRoute
  '/surgical-guide': typeof SurgicalGuideRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/veneers': typeof VeneersRoute
  '/world-wide-delivery': typeof WorldWideDeliveryRoute
  '/mdent-news/$slug': typeof MdentNewsSlugRoute
  '/mdent-news/': typeof MdentNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/5-year-warranty'
    | '/about-us'
    | '/booking-form'
    | '/careers'
    | '/clearsmile-aligners'
    | '/contact-us'
    | '/crowns'
    | '/dental-lab-uae'
    | '/dentures'
    | '/digital-impressions'
    | '/digital-products'
    | '/implant-restorations'
    | '/inlay-onlay'
    | '/inman-aligner'
    | '/mdent-team'
    | '/message-from-the-founder'
    | '/night-guards'
    | '/orthodontics'
    | '/our-clients'
    | '/past-events'
    | '/regular-impressions'
    | '/shade-matching'
    | '/sleep-apnea-appliance'
    | '/smile-design'
    | '/sports-guards'
    | '/surgical-guide'
    | '/terms-and-conditions'
    | '/upcoming-events'
    | '/veneers'
    | '/world-wide-delivery'
    | '/mdent-news/$slug'
    | '/mdent-news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/5-year-warranty'
    | '/about-us'
    | '/booking-form'
    | '/careers'
    | '/clearsmile-aligners'
    | '/contact-us'
    | '/crowns'
    | '/dental-lab-uae'
    | '/dentures'
    | '/digital-impressions'
    | '/digital-products'
    | '/implant-restorations'
    | '/inlay-onlay'
    | '/inman-aligner'
    | '/mdent-team'
    | '/message-from-the-founder'
    | '/night-guards'
    | '/orthodontics'
    | '/our-clients'
    | '/past-events'
    | '/regular-impressions'
    | '/shade-matching'
    | '/sleep-apnea-appliance'
    | '/smile-design'
    | '/sports-guards'
    | '/surgical-guide'
    | '/terms-and-conditions'
    | '/upcoming-events'
    | '/veneers'
    | '/world-wide-delivery'
    | '/mdent-news/$slug'
    | '/mdent-news'
  id:
    | '__root__'
    | '/'
    | '/5-year-warranty'
    | '/about-us'
    | '/booking-form'
    | '/careers'
    | '/clearsmile-aligners'
    | '/contact-us'
    | '/crowns'
    | '/dental-lab-uae'
    | '/dentures'
    | '/digital-impressions'
    | '/digital-products'
    | '/implant-restorations'
    | '/inlay-onlay'
    | '/inman-aligner'
    | '/mdent-team'
    | '/message-from-the-founder'
    | '/night-guards'
    | '/orthodontics'
    | '/our-clients'
    | '/past-events'
    | '/regular-impressions'
    | '/shade-matching'
    | '/sleep-apnea-appliance'
    | '/smile-design'
    | '/sports-guards'
    | '/surgical-guide'
    | '/terms-and-conditions'
    | '/upcoming-events'
    | '/veneers'
    | '/world-wide-delivery'
    | '/mdent-news/$slug'
    | '/mdent-news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R5YearWarrantyRoute: typeof R5YearWarrantyRoute
  AboutUsRoute: typeof AboutUsRoute
  BookingFormRoute: typeof BookingFormRoute
  CareersRoute: typeof CareersRoute
  ClearsmileAlignersRoute: typeof ClearsmileAlignersRoute
  ContactUsRoute: typeof ContactUsRoute
  CrownsRoute: typeof CrownsRoute
  DentalLabUaeRoute: typeof DentalLabUaeRoute
  DenturesRoute: typeof DenturesRoute
  DigitalImpressionsRoute: typeof DigitalImpressionsRoute
  DigitalProductsRoute: typeof DigitalProductsRoute
  ImplantRestorationsRoute: typeof ImplantRestorationsRoute
  InlayOnlayRoute: typeof InlayOnlayRoute
  InmanAlignerRoute: typeof InmanAlignerRoute
  MdentTeamRoute: typeof MdentTeamRoute
  MessageFromTheFounderRoute: typeof MessageFromTheFounderRoute
  NightGuardsRoute: typeof NightGuardsRoute
  OrthodonticsRoute: typeof OrthodonticsRoute
  OurClientsRoute: typeof OurClientsRoute
  PastEventsRoute: typeof PastEventsRoute
  RegularImpressionsRoute: typeof RegularImpressionsRoute
  ShadeMatchingRoute: typeof ShadeMatchingRoute
  SleepApneaApplianceRoute: typeof SleepApneaApplianceRoute
  SmileDesignRoute: typeof SmileDesignRoute
  SportsGuardsRoute: typeof SportsGuardsRoute
  SurgicalGuideRoute: typeof SurgicalGuideRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UpcomingEventsRoute: typeof UpcomingEventsRoute
  VeneersRoute: typeof VeneersRoute
  WorldWideDeliveryRoute: typeof WorldWideDeliveryRoute
  MdentNewsSlugRoute: typeof MdentNewsSlugRoute
  MdentNewsIndexRoute: typeof MdentNewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5-year-warranty': {
      id: '/5-year-warranty'
      path: '/5-year-warranty'
      fullPath: '/5-year-warranty'
      preLoaderRoute: typeof R5YearWarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-form': {
      id: '/booking-form'
      path: '/booking-form'
      fullPath: '/booking-form'
      preLoaderRoute: typeof BookingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clearsmile-aligners': {
      id: '/clearsmile-aligners'
      path: '/clearsmile-aligners'
      fullPath: '/clearsmile-aligners'
      preLoaderRoute: typeof ClearsmileAlignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowns': {
      id: '/crowns'
      path: '/crowns'
      fullPath: '/crowns'
      preLoaderRoute: typeof CrownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-lab-uae': {
      id: '/dental-lab-uae'
      path: '/dental-lab-uae'
      fullPath: '/dental-lab-uae'
      preLoaderRoute: typeof DentalLabUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentures': {
      id: '/dentures'
      path: '/dentures'
      fullPath: '/dentures'
      preLoaderRoute: typeof DenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-impressions': {
      id: '/digital-impressions'
      path: '/digital-impressions'
      fullPath: '/digital-impressions'
      preLoaderRoute: typeof DigitalImpressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-products': {
      id: '/digital-products'
      path: '/digital-products'
      fullPath: '/digital-products'
      preLoaderRoute: typeof DigitalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implant-restorations': {
      id: '/implant-restorations'
      path: '/implant-restorations'
      fullPath: '/implant-restorations'
      preLoaderRoute: typeof ImplantRestorationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inlay-onlay': {
      id: '/inlay-onlay'
      path: '/inlay-onlay'
      fullPath: '/inlay-onlay'
      preLoaderRoute: typeof InlayOnlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inman-aligner': {
      id: '/inman-aligner'
      path: '/inman-aligner'
      fullPath: '/inman-aligner'
      preLoaderRoute: typeof InmanAlignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdent-team': {
      id: '/mdent-team'
      path: '/mdent-team'
      fullPath: '/mdent-team'
      preLoaderRoute: typeof MdentTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-from-the-founder': {
      id: '/message-from-the-founder'
      path: '/message-from-the-founder'
      fullPath: '/message-from-the-founder'
      preLoaderRoute: typeof MessageFromTheFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-guards': {
      id: '/night-guards'
      path: '/night-guards'
      fullPath: '/night-guards'
      preLoaderRoute: typeof NightGuardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orthodontics': {
      id: '/orthodontics'
      path: '/orthodontics'
      fullPath: '/orthodontics'
      preLoaderRoute: typeof OrthodonticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-events': {
      id: '/past-events'
      path: '/past-events'
      fullPath: '/past-events'
      preLoaderRoute: typeof PastEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regular-impressions': {
      id: '/regular-impressions'
      path: '/regular-impressions'
      fullPath: '/regular-impressions'
      preLoaderRoute: typeof RegularImpressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shade-matching': {
      id: '/shade-matching'
      path: '/shade-matching'
      fullPath: '/shade-matching'
      preLoaderRoute: typeof ShadeMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep-apnea-appliance': {
      id: '/sleep-apnea-appliance'
      path: '/sleep-apnea-appliance'
      fullPath: '/sleep-apnea-appliance'
      preLoaderRoute: typeof SleepApneaApplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smile-design': {
      id: '/smile-design'
      path: '/smile-design'
      fullPath: '/smile-design'
      preLoaderRoute: typeof SmileDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-guards': {
      id: '/sports-guards'
      path: '/sports-guards'
      fullPath: '/sports-guards'
      preLoaderRoute: typeof SportsGuardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgical-guide': {
      id: '/surgical-guide'
      path: '/surgical-guide'
      fullPath: '/surgical-guide'
      preLoaderRoute: typeof SurgicalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-events': {
      id: '/upcoming-events'
      path: '/upcoming-events'
      fullPath: '/upcoming-events'
      preLoaderRoute: typeof UpcomingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veneers': {
      id: '/veneers'
      path: '/veneers'
      fullPath: '/veneers'
      preLoaderRoute: typeof VeneersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-wide-delivery': {
      id: '/world-wide-delivery'
      path: '/world-wide-delivery'
      fullPath: '/world-wide-delivery'
      preLoaderRoute: typeof WorldWideDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdent-news/': {
      id: '/mdent-news/'
      path: '/mdent-news'
      fullPath: '/mdent-news/'
      preLoaderRoute: typeof MdentNewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdent-news/$slug': {
      id: '/mdent-news/$slug'
      path: '/mdent-news/$slug'
      fullPath: '/mdent-news/$slug'
      preLoaderRoute: typeof MdentNewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R5YearWarrantyRoute: R5YearWarrantyRoute,
  AboutUsRoute: AboutUsRoute,
  BookingFormRoute: BookingFormRoute,
  CareersRoute: CareersRoute,
  ClearsmileAlignersRoute: ClearsmileAlignersRoute,
  ContactUsRoute: ContactUsRoute,
  CrownsRoute: CrownsRoute,
  DentalLabUaeRoute: DentalLabUaeRoute,
  DenturesRoute: DenturesRoute,
  DigitalImpressionsRoute: DigitalImpressionsRoute,
  DigitalProductsRoute: DigitalProductsRoute,
  ImplantRestorationsRoute: ImplantRestorationsRoute,
  InlayOnlayRoute: InlayOnlayRoute,
  InmanAlignerRoute: InmanAlignerRoute,
  MdentTeamRoute: MdentTeamRoute,
  MessageFromTheFounderRoute: MessageFromTheFounderRoute,
  NightGuardsRoute: NightGuardsRoute,
  OrthodonticsRoute: OrthodonticsRoute,
  OurClientsRoute: OurClientsRoute,
  PastEventsRoute: PastEventsRoute,
  RegularImpressionsRoute: RegularImpressionsRoute,
  ShadeMatchingRoute: ShadeMatchingRoute,
  SleepApneaApplianceRoute: SleepApneaApplianceRoute,
  SmileDesignRoute: SmileDesignRoute,
  SportsGuardsRoute: SportsGuardsRoute,
  SurgicalGuideRoute: SurgicalGuideRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UpcomingEventsRoute: UpcomingEventsRoute,
  VeneersRoute: VeneersRoute,
  WorldWideDeliveryRoute: WorldWideDeliveryRoute,
  MdentNewsSlugRoute: MdentNewsSlugRoute,
  MdentNewsIndexRoute: MdentNewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
